version: 2.1

orbs:
  architect: giantswarm/architect@0.4.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: hello-operator                     # change this
          filters:
            tags:
              only: /^v.*/

      - architect/go-test:
          name: test
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: docker
          image: "quay.io/giantswarm/master-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "master-operator"
          requires:
            - docker
          filters:
            tags:
              only: /^v.*/